### ISSUE TITLE
Explore supporting newer TSS revisions

### ISSUE THREAD

**Issue by zanebeckwith** [xaptum/xaptum-tpm#21]
The newest version of the IBM TPM2.0 (1119) simulator has some nice features:
- Support for a device file interface (rather than TCP)
- Support for building against openssl v1.1 rather than v1.0
  - This is nice for building on Stretch, which uses v1.1

However, the 1119 version of the simulator says it's off the revision 146 of the TSS spec. Running our unit tests against this version of the simulator fails:
- `create_load_evict_test` fails when initially run, then magically succeeds on subsequent runs
- `tss2_sys_create-test` fails, somewhere in the create call

It might be nice to support this newest revision of the spec, and thus of the simulator. However, we also need to make sure this still works with the current Infineon chips we actually use.

**Comment by drbild** [comment]
Not disagreeing, but one comment.

One reason (among others) for creating `xaptum-tpm` is to have a stable interface for the functions we need. We don't want the rest of our ecosystem (`xtt`, customers, etc.) constantly chasing the ever-changing TSS spec or implementations.

We currently need to support the hardware we're shipping, nothing else.  Anyone not doing Xaptum things with their TPM shouldn't be using this library; they should be using a full TSS, like the one from Intel.

All that said, if r146 is compatible with our hardware and moving to that makes our development environment more efficient (simulator with dev interface, so we can stop supporting two interfaces), it seems like updating could be a win.

**Comment by zanebeckwith** [comment]
Right, the reason this came up is simply that I can't get the simulator version we use building on Stretch (because of the openssl mismatch). The device-file testing would be nice, to test our (eventual) functionality for that. But, yea, the real reason for this issue is to be able to run simulated tests on Stretch. The most-recent simulator release is the first to support openssl v1.1.

**Comment by drbild** [comment]
:+1:

**Comment by zanebeckwith** [comment]
Obsoleted by #43 

Closing
